"use client";
import {useEffect,useState} from "react";import {ExternalLink,ShieldCheck} from "lucide-react";import type {TokenAnalytics} from "@/types/token";import {ageFrom,compactNumber,formatSupply,shortenAddress} from "@/lib/utils/format";import {CopyButton} from "@/components/shared/CopyButton";import {PriceChart} from "./PriceChart";
export function TokenView({address}:{address:string}){
 const [data,setData]=useState<TokenAnalytics|null>(null),[error,setError]=useState("");
 useEffect(()=>{fetch(`/api/token/${address}`).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error?.message);return body}).then(setData).catch(reason=>setError(reason.message))},[address]);
 if(error)return <div className="panel" style={{padding:32}}><h2>Unable to analyze token</h2><p className="muted">{error}</p></div>;
 if(!data)return <div className="panel" style={{padding:50,textAlign:"center"}}><p>Reading contract metadata…</p><p className="muted">Connecting to Robinhood Chain</p></div>;
 const {token,metrics,risk}=data;const explorerBase=token.explorerUrl.split("/address/")[0];
 const stats=[["Market Cap",compactNumber(metrics?.marketCapUsd,true)],["FDV",compactNumber(metrics?.fdvUsd,true)],["24H Volume",compactNumber(metrics?.volume24hUsd,true)],["Liquidity",compactNumber(metrics?.liquidityUsd,true)],["Holders",data.holderSummary?.holderCount?.toLocaleString()??"Unavailable"],["24H Buys",metrics?.buys24h?.toLocaleString()??"—"],["24H Sells",metrics?.sells24h?.toLocaleString()??"—"],["Total Supply",formatSupply(token.totalSupply,token.decimals)]];
 return <>
  <section className="panel token-header"><div><p className="eyebrow">{token.chainId} · {token.symbol}</p><h1>{token.name}</h1><div className="address-row"><code className="muted" title={token.address}>{shortenAddress(token.address)}</code><CopyButton value={token.address}/><a href={token.explorerUrl} target="_blank" rel="noreferrer" aria-label="Open contract in explorer"><ExternalLink size={18}/></a></div></div><div className="price"><p className="eyebrow">Price</p><div>{compactNumber(metrics?.priceUsd,true)}</div><span className={metrics?.priceChange24h!=null&&metrics.priceChange24h<0?"red":"green"}>{metrics?.priceChange24h==null?"Market data unavailable":`${metrics.priceChange24h.toFixed(2)}% 24h`}</span></div></section>
  <section className="stat-grid">{stats.map(([key,value])=><div key={key}><span className="eyebrow">{key}</span><strong>{value}</strong></div>)}</section>
  <div className="token-grid"><PriceChart points={data.priceHistory}/><section className="panel risk"><ShieldCheck/><p className="eyebrow">HoodLens Risk Score</p><div className="score">{risk.score}<span>/100</span></div><strong>{risk.level}</strong><div>{risk.deductions.length?risk.deductions.map(item=><div className="deduction" key={item.label}><div><span>{item.label}</span><span className="red">−{item.points}</span></div><small className="muted">{item.detail}</small></div>):<p className="muted">No deductions from currently available inputs.</p>}</div></section></div>
  <section className="detail-grid"><div className="panel detail"><h2>Holder distribution</h2>{data.holderSummary?<p className="muted">Top holder {data.holderSummary.topHolderPercentage?.toFixed(2)??"—"}% · Top 10 {data.holderSummary.top10Percentage?.toFixed(2)??"—"}%</p>:<p className="muted">Holder information is currently unavailable.</p>}<div className="scroll"><table><thead><tr><th>Address</th><th>Balance</th><th>Supply %</th></tr></thead><tbody>{data.holders.slice(0,10).map(holder=><tr key={holder.address}><td><a href={`${explorerBase}/address/${holder.address}`} target="_blank" rel="noreferrer">{holder.label??shortenAddress(holder.address)}</a></td><td>{formatSupply(holder.balance,token.decimals)}</td><td>{holder.percentage.toFixed(2)}%</td></tr>)}</tbody></table></div></div>
  <div className="panel detail"><h2>Recent transactions</h2>{data.transactions.length?<div className="scroll"><table><thead><tr><th>Type</th><th>Wallet</th><th>Amount</th><th>Age</th></tr></thead><tbody>{data.transactions.map((tx,index)=><tr key={`${tx.hash}-${index}`}><td>{tx.type}</td><td>{tx.wallet?shortenAddress(tx.wallet):"—"}</td><td>{tx.tokenAmount??"—"}</td><td><a href={tx.explorerUrl} target="_blank" rel="noreferrer">{ageFrom(tx.timestamp)}</a></td></tr>)}</tbody></table></div>:<p className="muted">No recent transactions available.</p>}</div>
  <div className="panel detail"><h2>Liquidity pools</h2>{data.pools.length?data.pools.slice(0,8).map(pool=><div className="pool" key={pool.address}><div><strong>{pool.name}</strong><small className="muted">{pool.dex}</small></div><span>{compactNumber(pool.liquidityUsd,true)}</span></div>):<p className="muted">Liquidity information is currently unavailable.</p>}</div></section>
  <p className="muted methodology">Holder concentration excludes only zero/burn addresses and contracts confidently labeled as pools or pairs by Blockscout. Transfers are not classified as buys or sells without DEX trade evidence. Updated {ageFrom(data.lastUpdated)} ago.</p>
 </>
}
